#!/usr/bin/env bash
# Doc-consistency gate. Cheap (no rebuild) — safe at session start and pre-commit.
#
# 2026-07-26 REWRITE #2 — from regex-whitelist to generate-and-diff.
#
# The history of this file is itself the argument for the change:
#   v1 piped two of five checks into `while read` (a subshell), so their `fail=1` could
#      not propagate. Exited 0 with six stale "276"s in HANDOFF.md.
#   v2 fixed the subshells but only regex-matched SPECIFIC PHRASINGS of the matched
#      count. It exited 0 while CLAUDE.md said 484/635, notes/WORK_MAP.md said 281 on
#      seven lines, and .claude/agents/function-mapper.md said 475 — because nobody had
#      encoded those phrasings. A whitelist only catches what someone remembered.
#
# v3 principle: A GENERATED NUMBER CANNOT ROT, AND A BYTE-DIFF IS TOTAL.
#   1. notes/COUNTS.md is generated by tools/gen_counts.sh -> regenerate and byte-diff.
#   2. progress.md / HANDOFF.md carry a generated block between markers -> byte-diff.
#   3. Every other doc must contain NO count-shaped claims; they point at COUNTS.md.
#
# DOC_ROOT=<dir> scans docs from an alternate directory. That is what lets the gate
# self-test in adversarial_audit.sh run against a throwaway copy instead of mutating the
# real HANDOFF.md — a session killed mid-audit used to leave a fake "999 matched" behind.
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
source .venv/bin/activate 2>/dev/null || true
DOC_ROOT="${DOC_ROOT:-.}"

DEFECTS=()
def() { DEFECTS+=("$1"); }

JSON=$(tools/gen_counts.sh --json 2>/dev/null) || {
  echo "check_docs: cannot get census — build first (make CPP=cpp build_rock_neo_only)"; exit 2; }
get() { printf '%s' "$JSON" | python3 -c "import json,sys;print(json.load(sys.stdin)['$1'])"; }
N=$(get matched); S=$(get active_stubs); CMAP=$(get c_mapped)
UNSPLIT=$(get unsplit_raw); TOTAL=$(get main_exe_total); WHOLE=$(get whole_game)

echo "authoritative: $N matched / $CMAP C-mapped ($(get pct_slice)%)"
echo "               $N / $TOTAL main exe ($(get pct_main_exe)%) — $UNSPLIT still unsplit raw asm"
echo "               $N / ~$WHOLE whole game ($(get pct_whole_game)%) · $S active stubs"

# --------------------------------------------------------------- 1. COUNTS.md byte-diff
if ! tools/gen_counts.sh --stdout 2>/dev/null | diff -q - "$DOC_ROOT/notes/COUNTS.md" >/dev/null 2>&1; then
  def "notes/COUNTS.md differs from tools/gen_counts.sh output — run: tools/gen_counts.sh"
fi

# ------------------------------------------------- 2. generated blocks in the live docs
block() {
  cat <<EOF
| metric | value |
|---|---|
| matched functions | **$N** |
| C-mapped slice | $N / **$CMAP** = $(get pct_slice)% |
| main executable | $N / **$TOTAL** = **$(get pct_main_exe)%** |
| **whole game** | $N / **~$WHOLE** = **~$(get pct_whole_game)%** |
| active INCLUDE_ASM stubs | **$S** |
| still unsplit raw asm | **$UNSPLIT** functions in \`asm/rock_neo/*.s\` |
EOF
}
for f in progress.md HANDOFF.md; do
  p="$DOC_ROOT/$f"; [ -f "$p" ] || continue
  if ! grep -q 'BEGIN GENERATED COUNTS' "$p"; then
    def "$f has no <!-- BEGIN GENERATED COUNTS --> block (its numbers are hand-typed and will rot)"
    continue
  fi
  have=$(awk '/BEGIN GENERATED COUNTS/{f=1;next} /END GENERATED COUNTS/{f=0} f' "$p")
  [ "$have" = "$(block)" ] || def "$f generated block is stale — run: tools/sync_docs.sh"
done

# ------------------------------- 3. no count-shaped claims in the hand-written docs
# These must delegate to notes/COUNTS.md rather than restate numbers. Any 3-4 digit number
# next to count language is a claim nothing regenerates. This is the check that would have
# caught CLAUDE.md's 484/635 and function-mapper.md's 475.
PROSE="CLAUDE.md notes/WORK_MAP.md notes/STRATEGY.md .claude/agents/function-mapper.md .claude/agents/build-runner.md"
ALLOW="205|2026|0x[0-9A-Fa-f]+|3000|2\.7\.2"     # legitimately-not-a-completion-count
for f in $PROSE; do
  p="$DOC_ROOT/$f"; [ -f "$p" ] || continue
  while IFS= read -r hit; do
    ln=${hit%%:*}; txt=${hit#*:}
    case "$txt" in *"[SUPERSEDED"*|*GENERATED*|*COUNTS.md*) continue;; esac
    nums=$(printf '%s' "$txt" | grep -oE '\b[0-9]{3,4}\b' | grep -vE "^($ALLOW)$" | tr '\n' ' ')
    [ -z "$nums" ] || def "$f:$ln restates counts ($nums) — point at notes/COUNTS.md: $(printf '%.65s' "$txt")"
  done < <(grep -nEi '(matched|active stub|C-mapped|denominator|unsplit|fully mapped|functions in)' "$p" 2>/dev/null)
done

# --------------------------------------------------------- 4. rulebook self-consistency
# NOTE: `$(grep -c ... || echo 0)` yields "0\n0" on no-match (grep prints 0 AND exits 1),
# which never compares equal to 0. Use a plain if-grep instead.
if grep -q 'ONLY authoritative matched count is `tools/census.py' "$DOC_ROOT/notes/LESSONS.md" 2>/dev/null; then
  def "notes/LESSONS.md names census.py as THE authority while CLAUDE.md names audit_count.sh"
fi

if [ ${#DEFECTS[@]} -eq 0 ]; then echo "docs consistent"; exit 0; fi
printf '  DEFECT: %s\n' "${DEFECTS[@]}"
echo "DOCS INCONSISTENT (${#DEFECTS[@]}) — fix before claiming progress"
exit 1
