#!/usr/bin/env bash
# GENERATE notes/COUNTS.md (and build/counts.json) from the built objects.
#
# Why this exists: every hand-written number in this repo has rotted at least once.
# notes/COUNTS.md was 20 days stale (223/261 against a real 281/203) while a regex gate
# reported "docs consistent", because the gate could only check the phrasings someone
# remembered to encode. A regex whitelist can never be complete; a byte-diff of a
# GENERATED file is total. So: nothing in COUNTS.md is typed by a human any more.
#
#   tools/gen_counts.sh          -> write notes/COUNTS.md + build/counts.json
#   tools/gen_counts.sh --stdout -> print the file, write nothing (used by check_docs.sh)
#   tools/gen_counts.sh --json   -> print counts.json only
#
# Requires a build (census.py reads build/src/rock_neo/*.o).
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
source .venv/bin/activate 2>/dev/null || true

CENSUS=$(python3 tools/census.py --matched 2>/dev/null | grep -iE '^total:')
[ -n "$CENSUS" ] || { echo "gen_counts: no census — run 'make CPP=cpp build_rock_neo_only' first" >&2; exit 2; }

CMAP=$(printf '%s' "$CENSUS" | grep -oE '[0-9]+ in object files'  | grep -oE '[0-9]+')
STUBS=$(printf '%s' "$CENSUS" | grep -oE '[0-9]+ active stubs'    | grep -oE '[0-9]+')
MATCHED=$(printf '%s' "$CENSUS" | grep -oE '[0-9]+ matched'       | grep -oE '[0-9]+')
# UNSPLIT must come from the map, NOT a grep over asm/rock_neo/*.s: stale chunk files
# linger there after a re-split (gitignored, nothing cleans them) and a raw grep
# double-counts functions that also live in a linked chunk — it read 834 against a real
# 614, pushing the main-exe total to 1339 against a real 1119. tools/gen_map.py filters
# to chunks rock_neo.ld actually references.
MAP=build/function_map.json
[ -f "$MAP" ] || tools/gen_map.py >/dev/null 2>&1
mapget() { python3 -c "import json;print(json.load(open('$MAP'))['summary']['$1'])" 2>/dev/null; }
UNSPLIT=$(mapget unsplit_engine)
# Stage realm. census.py is authoritative for the ENGINE only (it globs
# build/src/rock_neo/*.o); the map is authoritative for stages. Read each from the tool
# that can actually see it, and CROSS-CHECK the overlap — two tools quoting different
# engine numbers is precisely the drift this project keeps getting bitten by.
STAGE_MATCHED=$(mapget stage_matched)
MAP_ENGINE_MATCHED=$(mapget engine_matched)
if [ -n "$MAP_ENGINE_MATCHED" ] && [ "$MAP_ENGINE_MATCHED" != "$MATCHED" ]; then
  echo "gen_counts: DISAGREEMENT — census.py says $MATCHED engine matched, gen_map.py says $MAP_ENGINE_MATCHED." >&2
  echo "gen_counts: refusing to emit a number. Rebuild (make CPP=cpp) then re-run tools/gen_map.py." >&2
  exit 3
fi
MATCHED_TOTAL=$(( MATCHED + STAGE_MATCHED ))
RAWGREP=$(grep -c INCLUDE_ASM src/rock_neo/*.c 2>/dev/null | awk -F: '{s+=$2} END{print s+0}')
TOTAL=$(( CMAP + UNSPLIT ))
SHADOWED=$(( RAWGREP - STUBS ))

# Whole-game denominator. Single source of truth is tools/gen_map.py, which derives it
# from the asm itself. Two tools publishing different whole-game numbers (8129 vs 8183)
# is the drift this project keeps getting bitten by, so read it from the map.
OVL_UNIQUE=$(mapget stage_unique)
SDK=$(mapget sdk_total)
WHOLE=$(( TOTAL + OVL_UNIQUE + SDK ))

pct() { awk "BEGIN{printf \"%.1f\", 100*$1/$2}"; }
P_SLICE=$(pct "$MATCHED" "$CMAP"); P_EXE=$(pct "$MATCHED" "$TOTAL")
P_GAME=$(pct "$MATCHED_TOTAL" "$WHOLE"); P_STAGE=$(pct "$STAGE_MATCHED" "$OVL_UNIQUE")

if [ "${1:-}" = "--json" ]; then
  printf '{"matched":%s,"stage_matched":%s,"matched_total":%s,"c_mapped":%s,"active_stubs":%s,"unsplit_raw":%s,"main_exe_total":%s,"overlay_unique":%s,"whole_game":%s,"pct_slice":%s,"pct_main_exe":%s,"pct_stage":%s,"pct_whole_game":%s}\n' \
    "$MATCHED" "$STAGE_MATCHED" "$MATCHED_TOTAL" "$CMAP" "$STUBS" "$UNSPLIT" "$TOTAL" "$OVL_UNIQUE" "$WHOLE" "$P_SLICE" "$P_EXE" "$P_STAGE" "$P_GAME"
  exit 0
fi

render() {
cat <<EOF
# Counts — reconciliation of the several numbers this project quotes

<!-- GENERATED BY tools/gen_counts.sh — DO NOT EDIT BY HAND.
     tools/check_docs.sh regenerates this file and byte-diffs it against the committed
     copy, so any hand edit here is a hard commit failure. Change the generator instead. -->

Every number below is computed from the built objects, never typed. Regenerate with
\`tools/gen_counts.sh\`. Authoritative verification (rebuild + hash + raw cmp) is a
separate, slower step: \`tools/audit_count.sh\`.

| Number | Value | Meaning |
|---|---|---|
| \`F .text\` in all rock_neo \`.o\` | **$CMAP** | Functions currently split into C TUs. **NOT the mission denominator.** |
| Functions still unsplit (raw asm) | **$UNSPLIT** | \`glabel\`s in \`asm/rock_neo/*.s\`, never split into a C TU. |
| **Game functions in ROCK_NEO.EXE** | **$TOTAL** | $CMAP + $UNSPLIT. The MAIN-EXE denominator. |
| Unique overlay functions | **~$OVL_UNIQUE** | Measured by \`tools/overlay_scope.py\`; deduped across 205 overlays. |
| Sony PSY-Q SDK in the exe | **$SDK** | \`asm/rock_neo/psxsdk/code.s\`, linked by rock_neo.ld. NOT Capcom code; matchable from published source. Invisible to every count before 2026-07-28 because the map globbed \`asm/rock_neo/*.s\` and never descended into subdirectories. |
| **Whole-game functions** | **~$WHOLE** | $TOTAL main exe + ~$OVL_UNIQUE overlay + $SDK SDK. THE whole-game denominator. |
| Matched — ENGINE (real C in tree) | **$MATCHED** | $CMAP − $STUBS. \`census.py --matched\`, authoritative for the main exe. |
| Matched — STAGE (unique bodies) | **$STAGE_MATCHED** | Stage overlay functions with real C. Invisible to \`census.py\` (it globs only \`build/src/rock_neo/*.o\`); read from \`gen_map.py\`, which proves linkage from each overlay's own \`.map\`. |
| **Matched — WHOLE GAME** | **$MATCHED_TOTAL** | $MATCHED engine + $STAGE_MATCHED stage. |
| Active INCLUDE_ASM stubs | **$STUBS** | Stubs still pulled in AFTER cpp (ifdef-aware). |
| Raw \`grep -c INCLUDE_ASM\` | $RAWGREP | **DO NOT USE.** Blind to \`#define ACCEPT_REORDERING_BULLSHIT\` in game.c/sub_scrn.c; $SHADOWED stubs are shadowed by an active \`#else\` body. Un-gating one is a NO-OP that reads as +1 — this caused the 2026-07-19 inflation. |
| By function count (C-mapped slice) | **${P_SLICE}%** | $MATCHED / $CMAP — the number historically quoted. Overstates the mission. |
| By function count (main exe) | **${P_EXE}%** | $MATCHED / $TOTAL. |
| By function count (stage realm) | **${P_STAGE}%** | $STAGE_MATCHED / ~$OVL_UNIQUE. |
| **By function count (WHOLE GAME)** | **~${P_GAME}%** | $MATCHED_TOTAL / ~$WHOLE. The honest number. |

## Splitting is not progress
A phase-0 split MOVES a function from the unsplit bucket into the C-mapped bucket. It
raises \`$CMAP\` and lowers \`$UNSPLIT\` and leaves **$TOTAL unchanged**. Only a rise in
**matched** is progress.

## Always name which denominator
The 2026-07-26 audit found this project had reported \`matched/C-mapped\` for months while
$UNSPLIT functions sat in \`asm/rock_neo/*.s\`, linked by \`rock_neo.ld\` and invisible to
\`census.py\` (which reads only \`build/src/rock_neo/*.o\`). Same defect class as the
ACCEPT_REORDERING_BULLSHIT inflation: a completion metric defined by what a tool parses
rather than by the target binary.

## Two realms, two authorities
\`census.py\` can only see \`build/src/rock_neo/*.o\`, so it is authoritative for the ENGINE
and structurally blind to stages. \`gen_map.py\` sees both. Until the first stage match
landed (2026-07-26) the two agreed by accident, because the stage count was zero — the
blind spot and the truth were the same number. \`gen_counts.sh\` now cross-checks the two
on the engine figure and refuses to emit anything if they disagree.

## Function count runs ahead of code volume
Small functions were matched first, so function-count progress overstates volume progress.
Size distribution of what remains: \`tools/analyze_raw_asm.py\`.
EOF
}

if [ "${1:-}" = "--stdout" ]; then render; exit 0; fi

render > notes/COUNTS.md
mkdir -p build
tools/gen_counts.sh --json > build/counts.json
echo "gen_counts: wrote notes/COUNTS.md and build/counts.json ($MATCHED matched / $CMAP C-mapped / $TOTAL main exe / ~$WHOLE whole game)"
