#!/usr/bin/env bash
# GENERATE notes/COUNTS.md (and build/counts.json) from the built objects.
#
# Why this exists: every hand-written number in this repo has rotted at least once.
# notes/COUNTS.md was 20 days stale (223/261 against a real 281/203) while a regex gate
# reported "docs consistent", because the gate could only check the phrasings someone
# remembered to encode. A regex whitelist can never be complete; a byte-diff of a
# GENERATED file is total. So: nothing in COUNTS.md is typed by a human any more.
#
#   tools/gen_counts.sh          -> write notes/COUNTS.md + build/counts.json
#   tools/gen_counts.sh --stdout -> print the file, write nothing (used by check_docs.sh)
#   tools/gen_counts.sh --json   -> print counts.json only
#
# Requires a build (census.py reads build/src/rock_neo/*.o).
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
source .venv/bin/activate 2>/dev/null || true

CENSUS=$(python3 tools/census.py --matched 2>/dev/null | grep -iE '^total:')
[ -n "$CENSUS" ] || { echo "gen_counts: no census — run 'make CPP=cpp build_rock_neo_only' first" >&2; exit 2; }

CMAP=$(printf '%s' "$CENSUS" | grep -oE '[0-9]+ in object files'  | grep -oE '[0-9]+')
STUBS=$(printf '%s' "$CENSUS" | grep -oE '[0-9]+ active stubs'    | grep -oE '[0-9]+')
MATCHED=$(printf '%s' "$CENSUS" | grep -oE '[0-9]+ matched'       | grep -oE '[0-9]+')
UNSPLIT=$(grep -h '^glabel' asm/rock_neo/*.s 2>/dev/null | wc -l | tr -d ' ')
RAWGREP=$(grep -c INCLUDE_ASM src/rock_neo/*.c 2>/dev/null | awk -F: '{s+=$2} END{print s+0}')
TOTAL=$(( CMAP + UNSPLIT ))
SHADOWED=$(( RAWGREP - STUBS ))

# Whole-game denominator. Single source of truth is tools/gen_map.py, which derives it
# from the asm itself. Two tools publishing different whole-game numbers (8129 vs 8183)
# is the drift this project keeps getting bitten by, so read it from the map.
OVL_UNIQUE=$(python3 -c "import json;print(json.load(open('build/function_map.json'))['summary']['stage_unique'])" 2>/dev/null \
             || { tools/gen_map.py >/dev/null 2>&1; python3 -c "import json;print(json.load(open('build/function_map.json'))['summary']['stage_unique'])" 2>/dev/null; } \
             || echo 7064)
WHOLE=$(( TOTAL + OVL_UNIQUE ))

pct() { awk "BEGIN{printf \"%.1f\", 100*$1/$2}"; }
P_SLICE=$(pct "$MATCHED" "$CMAP"); P_EXE=$(pct "$MATCHED" "$TOTAL"); P_GAME=$(pct "$MATCHED" "$WHOLE")

if [ "${1:-}" = "--json" ]; then
  printf '{"matched":%s,"c_mapped":%s,"active_stubs":%s,"unsplit_raw":%s,"main_exe_total":%s,"overlay_unique":%s,"whole_game":%s,"pct_slice":%s,"pct_main_exe":%s,"pct_whole_game":%s}\n' \
    "$MATCHED" "$CMAP" "$STUBS" "$UNSPLIT" "$TOTAL" "$OVL_UNIQUE" "$WHOLE" "$P_SLICE" "$P_EXE" "$P_GAME"
  exit 0
fi

render() {
cat <<EOF
# Counts — reconciliation of the several numbers this project quotes

<!-- GENERATED BY tools/gen_counts.sh — DO NOT EDIT BY HAND.
     tools/check_docs.sh regenerates this file and byte-diffs it against the committed
     copy, so any hand edit here is a hard commit failure. Change the generator instead. -->

Every number below is computed from the built objects, never typed. Regenerate with
\`tools/gen_counts.sh\`. Authoritative verification (rebuild + hash + raw cmp) is a
separate, slower step: \`tools/audit_count.sh\`.

| Number | Value | Meaning |
|---|---|---|
| \`F .text\` in all rock_neo \`.o\` | **$CMAP** | Functions currently split into C TUs. **NOT the mission denominator.** |
| Functions still unsplit (raw asm) | **$UNSPLIT** | \`glabel\`s in \`asm/rock_neo/*.s\`, never split into a C TU. |
| **Game functions in ROCK_NEO.EXE** | **$TOTAL** | $CMAP + $UNSPLIT. The MAIN-EXE denominator. |
| Unique overlay functions | **~$OVL_UNIQUE** | Measured by \`tools/overlay_scope.py\`; deduped across 205 overlays. |
| **Whole-game functions** | **~$WHOLE** | $TOTAL main exe + ~$OVL_UNIQUE overlay. THE whole-game denominator. |
| Matched (real C in tree) | **$MATCHED** | $CMAP − $STUBS. |
| Active INCLUDE_ASM stubs | **$STUBS** | Stubs still pulled in AFTER cpp (ifdef-aware). |
| Raw \`grep -c INCLUDE_ASM\` | $RAWGREP | **DO NOT USE.** Blind to \`#define ACCEPT_REORDERING_BULLSHIT\` in game.c/sub_scrn.c; $SHADOWED stubs are shadowed by an active \`#else\` body. Un-gating one is a NO-OP that reads as +1 — this caused the 2026-07-19 inflation. |
| By function count (C-mapped slice) | **${P_SLICE}%** | $MATCHED / $CMAP — the number historically quoted. Overstates the mission. |
| By function count (main exe) | **${P_EXE}%** | $MATCHED / $TOTAL. |
| **By function count (WHOLE GAME)** | **~${P_GAME}%** | $MATCHED / ~$WHOLE. The honest number. |

## Splitting is not progress
A phase-0 split MOVES a function from the unsplit bucket into the C-mapped bucket. It
raises \`$CMAP\` and lowers \`$UNSPLIT\` and leaves **$TOTAL unchanged**. Only a rise in
**matched** is progress.

## Always name which denominator
The 2026-07-26 audit found this project had reported \`matched/C-mapped\` for months while
$UNSPLIT functions sat in \`asm/rock_neo/*.s\`, linked by \`rock_neo.ld\` and invisible to
\`census.py\` (which reads only \`build/src/rock_neo/*.o\`). Same defect class as the
ACCEPT_REORDERING_BULLSHIT inflation: a completion metric defined by what a tool parses
rather than by the target binary.

## Function count runs ahead of code volume
Small functions were matched first, so function-count progress overstates volume progress.
Size distribution of what remains: \`tools/analyze_raw_asm.py\`.
EOF
}

if [ "${1:-}" = "--stdout" ]; then render; exit 0; fi

render > notes/COUNTS.md
mkdir -p build
tools/gen_counts.sh --json > build/counts.json
echo "gen_counts: wrote notes/COUNTS.md and build/counts.json ($MATCHED matched / $CMAP C-mapped / $TOTAL main exe / ~$WHOLE whole game)"
